/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Owned } from "./Owned";
export type { Pausable } from "./Pausable";
export type { ProofOfValueActivityMining } from "./ProofOfValueActivityMining";
export type { ProofOfValueValidators } from "./ProofOfValueValidators";
