/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Detailed__factory } from "./ERC20Detailed__factory";
export { IERC20__factory } from "./IERC20__factory";
