/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
import type * as openzeppelinSolidity230 from "./openzeppelin-solidity-2.3.0";
export type { openzeppelinSolidity230 };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { IStakingRewards } from "./contracts/interfaces/IStakingRewards";
export { IStakingRewards__factory } from "./factories/contracts/interfaces/IStakingRewards__factory";
export type { Owned } from "./contracts/Owned";
export { Owned__factory } from "./factories/contracts/Owned__factory";
export type { Pausable } from "./contracts/Pausable";
export { Pausable__factory } from "./factories/contracts/Pausable__factory";
export type { ProofOfValueActivityMining } from "./contracts/ProofOfValueActivityMining";
export { ProofOfValueActivityMining__factory } from "./factories/contracts/ProofOfValueActivityMining__factory";
export type { ProofOfValueValidators } from "./contracts/ProofOfValueValidators";
export { ProofOfValueValidators__factory } from "./factories/contracts/ProofOfValueValidators__factory";
export type { ERC20Detailed } from "./openzeppelin-solidity-2.3.0/contracts/token/ERC20/ERC20Detailed";
export { ERC20Detailed__factory } from "./factories/openzeppelin-solidity-2.3.0/contracts/token/ERC20/ERC20Detailed__factory";
export type { ReentrancyGuard } from "./openzeppelin-solidity-2.3.0/contracts/utils/ReentrancyGuard";
export { ReentrancyGuard__factory } from "./factories/openzeppelin-solidity-2.3.0/contracts/utils/ReentrancyGuard__factory";
